server:
  port: 8888

spring:
  application:
    name: "config-server"

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/piction-protocol/cloud-server-config-repo"

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password